### ISSUE TITLE
Code does not work under python2

### ISSUE THREAD

**Issue by KramerChristian** [HergenrotherLab/entry-cli#5]
I just tried to run the code under python2. When doing so, I get an AttributeError

Traceback (most recent call last):
  File "entry-cli-master/calc_props.py", line 395, in <module>
    main()
  File "entry-cli-master/calc_props.py", line 36, in main
    properties = average_properties(mol)
  File "entry-cli-master/calc_props.py", line 134, in average_properties
    mols = run_confab(mol)
  File "entry-cli-master/calc_props.py", line 216, in run_confab
    pff.DiverseConfGen(rmsd_cutoff, conf_cutoff, energy_cutoff, confab_verbose)
AttributeError: 'OBForceField' object has no attribute 'DiverseConfGen'

I am not sure whether this is due to python2. But if the code does not work under python2, it would be helpful if this is stated in the README.

**Comment by KramerChristian** [comment]
I now tested it under python 3. It works there, so seems to be a specific python2 problem.

**Comment by bdrown** [comment]
Thanks for the feedback. That's an odd error that I haven't seen in my testing with python 2.7.3 Which versions of python and openbabel are you working with?
